#!/bin/sh

set -ex

git clean -df
rm -f .test_queue_stats

export TEST_QUEUE_WORKERS=2 TEST_QUEUE_VERBOSE=1

if [ -f "Gemfile-$SUITE" ]; then
  export BUNDLE_GEMFILE="Gemfile-$SUITE"
else
  export BUNDLE_GEMFILE=Gemfile
fi

bundle install

vendor/bats/bin/bats test
